[project]
name = "obsidian-mcp"
version = "0.1.0"
description = "An MCP server to query your Obsidian vault."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
]
